### ISSUE TITLE
priority.priority.TooManyStreamsError

### ISSUE THREAD

**Issue by chantra** [decentfox/aioh2#16]
After using the same connection over and over, I eventually hit this error:

```
priority.priority.TooManyStreamsError: Refusing to insert 1001 streams into priority tree at once
```

The reason it seems is that `self._priority.remove_Stream(stream_id)` is never being called. Maybe and example usage would be https://twistedmatrix.com/trac/attachment/ticket/7460/7460_4.patch

**Comment by fantix** [comment]
I'll check this, thx for letting me know 😺

**Comment by chantra** [comment]
So it looks like all that is needed is to plug:

```
self._priority.remove_stream(event.stream_id)
```

in both `_stream_ended` and `_stream_reset` but that does not seem to play nice with the server side when running unittests assumably because this kills the stream when the server side still need to send data.

**Comment by LoicCaudron** [comment]
Hello !

I am currently working on DoH traffic and using the doh-proxy tool. I'm facing the same problem mentioned by @chantra . Is there any way to patch this in aioh2 or do it manually in the doh-proxy tool?

Could you possibly help me solve this problem?

Thanks in advance.
